# -*- coding: utf-8 -*-
"""weather_forecast

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1a9nZUNQsjltpiCak3R3MzjhJe0XMJPNI
"""

import requests

run = True

while run:
  print("We have about 200.000 cities with the information about their current weather in the database \n")
  city = input('which city do you want to know : ')

  try : 
    url = 'http://api.openweathermap.org/data/2.5/weather?q={}&appid=a04d860843675aebff2701a3d43d9c95&units=metric'.format(city)
    r = requests.get(url)
    weather_infor = r.json()

    name = weather_infor['name']
    condition = weather_infor['weather'][0]['description']
    temperature = weather_infor['main']['temp']
    humidity = weather_infor['main']['humidity']	  
    output_str =  'City : %s \nCondition: %s \nTemperature : %s \nHumidity : %s\n' % (name, condition, temperature, humidity)
  except:
    output_str = "we don't have information about this city. Please type again!"
  print(output_str)
  check = input("Do you want to continue ? : (Y/N)")
  if (check == 'N' or check == 'n'):
    run = False